### ISSUE TITLE
Pages - Broken usertemplates

### ISSUE THREAD

**Issue by wouterverstuyf** [forkcms/forkcms#3370]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | yes  |
| Version      | 5.9.3|

### Problem description

Adding a new user template is not possible. Tested on the demo and the popup doesn't render the fields.
A JS error is in the console.

### Steps to reproduce

Add a user template in the demo

**Comment by jessedobbelaere** [comment]
I noticed it too. Should be fixed when #3365 is merged in 👀

**Comment by wouterverstuyf** [comment]
> I noticed it too. Should be fixed when #3365 is merged in 👀

Thx. Not completely solved.
When I want to visit the html file by the path /src/Frontend... I get an Permission Denied. So I guess the html file is not accessible
